# Site settings
title: Adler Luiz
description: .

# User settings
username: Adler Luiz
user_description: .
user_title: Software Developer
email: adlerluiz10@gmail.com
twitter_username: adlerluiz
github_username:  adlerluiz
gplus_username:  AdlerLuizFreitas

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

gems:           ['jekyll-multiple-languages']
# The all languages used
languages:          ['pt-br', 'en']

# If not config, the first item of languages will be used as the default.
language_default:   'pt-br'